owner: ZonkeyZebra
repo: jwt-upptime

sites:
  - name: Pizza API
    url: https://pizza.jwt-pizza.click/

status-website:
  baseUrl: /jwt-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pizza API Status
  introTitle: "**Pizza API Status Page**"
  introMessage: Monitoring uptime and response times for the Pizza service.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
